# -*- coding: utf-8 -*-
"""Копия блокнота "PythonUrban_lab2.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oPXuC_Zwtec7gXuMSVN7UtxoQqBOqZe7

# Итоговый проект. Улицы. Объекты культурного наследия.
"""

# TODO собрать установку всех необходимых модулей в одном месте
!pip install geopandas 
!pip install mapclassify
!pip install osmnx

# TODO собрать импорты всех модулей в одном месте
import geopandas as gpd
import osmnx as ox
import numpy as np
import pandas as pd

TILES = "CartoDB positron"  # Название подложки для карт

# TODO указать любой район Санкт-Петербург из OSM https://wiki.openstreetmap.org/wiki/RU:%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3/%D0%A0%D0%B0%D0%B9%D0%BE%D0%BD%D1%8B
TERRITORY_NAME = "Петроградский район, Санкт-Петербург" # название территории для которой будут строиться слои

# TODO указать ссылку на файл из вашего github репозитория, которая начинается с https://raw.githubusercontent.com/
KGIOP_FILE_URL = "https://raw.githubusercontent.com/LizochkaSt/Laboratory_1/main/geojson%20%D1%81%D0%BB%D0%BE%D0%B8/kgiop_objects.geojson"  # ссылка на слой с объектами культурного наследия
STREETS_FILE_URL = "https://raw.githubusercontent.com/LizochkaSt/Laboratory_1/main/geojson%20%D1%81%D0%BB%D0%BE%D0%B8/streets.geojson"  # ссылка на слой с улицами

"""## Территория

### Загрузка территории из OSM (Extract)
"""

district = ox.geocode_to_gdf(TERRITORY_NAME) # TODO загрузить geodataframe с геометрией для территории TERRITORY_NAME

"""## Улицы

### Загрузка файла с улицами (Extract)
"""

# TODO отфильтровать улицы по маске геометрии территории полученной ранее
streets = gpd.read_file(STREETS_FILE_URL, mask=district)

"""### Обработка данных с улицами (Transform)"""

# TODO сгруппировать и объединить геометрии с одинаковыми названиями
streets = streets.dissolve(by="name")

"""### Сохранение слоя с улицами (Load)"""

# TODO переименовать столбцы в русские названия, кроме столбца geometry
streets.rename(columns={"name": "Имя"}, inplace=True)
# TODO для того чтобы переименовать индекс, нужно обратиться и нему и вызвать от него метод rename (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.rename.html)

# TODO сохранить слой в географической проекции в формате GeoJSON
streets.to_crs(4326).to_file('streets.geojson', driver='GeoJSON')

"""## Объекты культурного наследия

### Загрузка объектов культурного наследия (Extract)
"""

# TODO отфильтровать улицы по маске геометрии территории полученной ранее
objects = gpd.read_file(KGIOP_FILE_URL, mask=district)

"""### Обработка объектов культурного наследия (Transform)"""

# TODO добавить два столбца lon и lat, в которых будут долгота и широта 
objects["lon"] = objects.loc[:, objects.columns[8]] 
objects["lat"] = objects.loc[:, objects.columns[8]]

"""### Сохранение слоя с объектами культурного наследия (Load)"""

# TODO переименовать столбцы в русские названия, кроме столбца geometry
rename_columns = {
    "id": "Айди",
    "ensemble_name": "Название группы",
    "object_name": "Название объекта",
    "occurrence_time": "Время построения",
    "object_location": "Расположение обьекта",
    "historical_category": "Историческая категория",
    "normative_act": "Нормативный акт",
    "object_type": "Тип обьекта"
}
objects.rename(columns=rename_columns, inplace=True)

# TODO сохранить слой в географической проекции в формате GeoJSON
objects.to_crs(4326).to_file('cultural_objects.geojson', driver='GeoJSON')